config/routes.rb
RPGalot::Application.routes.draw do 
  resources :languages

  resources :levels

	root :to => 'home#index'
	
	match "login" => "user_sessions#new", :as => "login"
  match "logout" => "user_sessions#destroy", :as => "logout"

 	resources :user_sessions
  resources :character_feats
  resources :weapons
  resources :races
	resources :feats
  resources :deities
  resources :klass_skills
  resources :klass_alignments
  resources :klasses
  resources :alignments
  resources :skills
  resources :abilities
  resources :games
  resources :characters
  resources :campaigns
  resources :memberships
  resources :groups
  resources :users


	#map.connect ':controller/:action/:id'

  #map.connect ':controller/:action/:id.:format'
end

app/models/race.rb
class Race < ActiveRecord::Base
	# t.string :title, :null => false
	#   t.integer :speed, :null => false
	#   t.string :size, :null => false
		belongs_to :game, :class_name => 'Game', :foreign_key => :game_id	
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  # GET /races
  # GET /races.xml
  def index
    @races = Race.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @races }

			
    end
  end

  # GET /races/1
  # GET /races/1.xml
  def show
    @race = Race.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @race }

    end
  end

  # GET /races/new
  # GET /races/new.xml
  def new
    @race = Race.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @race }
    end
  end

  # GET /races/1/edit
  def edit
    @race = Race.find(params[:id])
  end

  # POST /races
  # POST /races.xml
  def create
    @race = Race.new(params[:race])

    respond_to do |format|
      if @race.save
        format.html { redirect_to(@race, :notice => 'Race was successfully created.') }
        format.xml  { render :xml => @race, :status => :created, :location => @race }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @race.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /races/1
  # PUT /races/1.xml
  def update
    @race = Race.find(params[:id])

    respond_to do |format|
      if @race.update_attributes(params[:race])
        format.html { redirect_to(@race, :notice => 'Race was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @race.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.xml
  def destroy
    @race = Race.find(params[:id])
    @race.destroy

    respond_to do |format|
      format.html { redirect_to(races_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/edit.html.erb
<h1>Editing race</h1>

<%= form_for(@race) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :speed %><br />
    <%= f.text_field :speed %>
  </p>
  <p>
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @race %> |
<%= link_to 'Back', races_path %>

app/views/races/index.html.erb
<h1>Listing races</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Speed</th>
    <th>Size</th>
  </tr>

<% @races.each do |race| %>
  <tr>
    <td><%=h race.title %></td>
    <td><%=h race.speed %></td>
    <td><%=h race.size %></td>
    <td><%= link_to 'Show', race %></td>
    <td><%= link_to 'Edit', edit_race_path(race) %></td>
    <td><%= link_to 'Destroy', race, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New race', new_race_path %>

app/views/races/new.html.erb
<h1>New race</h1>

<%= form_for(@race) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :speed %><br />
    <%= f.text_field :speed %>
  </p>
  <p>
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', races_path %>

app/views/races/show.html.erb
<p>
  <b>Title:</b>
  <%=h @race.title %>
</p>


<p>
  <b>Speed:</b>
  <%=h @race.speed %>
</p>

<p>
  <b>Size:</b>
  <%=h @race.size %>
</p>


<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'Back', races_path %>

app/views/races/show.json.erb
{
	'Race': '<%= @race.title %>
	'Speed': '<%= @race.speed %>
	'Size': '<%= @race.size %>
}  