config/routes.rb
RPGalot::Application.routes.draw do 
  resources :languages

  resources :levels

	root :to => 'home#index'
	
	match "login" => "user_sessions#new", :as => "login"
  match "logout" => "user_sessions#destroy", :as => "logout"

 	resources :user_sessions
  resources :character_feats
  resources :weapons
  resources :races
	resources :feats
  resources :deities
  resources :klass_skills
  resources :klass_alignments
  resources :klasses
  resources :alignments
  resources :skills
  resources :abilities
  resources :games
  resources :characters
  resources :campaigns
  resources :memberships
  resources :groups
  resources :users


	#map.connect ':controller/:action/:id'

  #map.connect ':controller/:action/:id.:format'
end

app/models/group.rb
class Group < ActiveRecord::Base
	# t.string :title
	# t.text :description
	# t.boolean :invite_only, :null => false, :default => false
	# t.integer :created_by_id, :null => false
	
	validates_presence_of :title, :created_by_id
	validates_uniqueness_of :title
	belongs_to :created_by, :class_name => 'User'
	has_many :created_campaigns, :class_name => 'Campaign', :foreign_key => :group_id
	has_many :memberships
	has_many :users, :through => :memberships
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.xml
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.xml
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.xml
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to(@group, :notice => 'Group was successfully created.') }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to(@group, :notice => 'Group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to(groups_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<% f.inputs do %>

  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :invite_only %>
	<%= f.input :created_by_id, :as => :select, :collection => User.all %>
	<%= f.input :user_ids, :as => :check_boxes, :collection => User.all, :label => 'Members'  %>


	<% f.buttons do %>
	  <%= f.commit_button %>
	<% end %>
	
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= semantic_form_for(@group) do |f| %>
	<%= render 'form', :f => f %>
<% end %>

<%= link_to 'View Group', @group %> |
<%= link_to 'Destroy Group', @group, :confirm => 'Are you sure?', :method => :delete %>

app/views/groups/index.html.erb
<div id="sheet_header">
	<span class="right"><%= link_to 'New Group', new_group_path %></span>
	<h2>Groups</h2>
</div>

<% @groups.each do |group| %>
	<div class="list">
	<table>
		<tr>
			<td class="description">
				<img src="/images/group.gif" alt"group photo" width="50px" />
			</td>
			<td>
				<table>
					<tr>
						<td class="description"> Title:</td>
						<td><strong><%= link_to h(group.title), group %></strong></td>
					</tr>
					<tr>
						<td class="description">Founder:</td>
						<td><%=link_to h(group.created_by.name), group.created_by%></td>
					</tr>
					<tr>
						<td class="description">Members:</td>
						<td><%=h group.memberships.count %> members</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
	</div>
<% end %>


<br />

app/views/groups/new.html.erb
<h1>New group</h1>

<%= semantic_form_for(@group) do |f| %>
		<%= render 'form', :f => f %>
<% end %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<div id="sheet_header">
	<span class="right"><%= link_to 'Edit', edit_group_path(@group) %> </span>
	<h2> <%=h @group.title %></h2>
</div>

<div id="sheet">

	<div id="avatar">
			<img src="/images/group.gif" alt"group photo" width="100px" />
	</div>


<p>
	<b>Founder:</b>
	<%=link_to h(@group.created_by.name), @group.created_by%>
</p>

<p>
  <b>Description:</b>
  <%=h @group.description %>
</p>

<p>
	<% if @group.invite_only == true %>
	<em>Invite Only</em>
	<% else %>
	<em>Open Group</em>
	<% end %>
</p>

<div class="section right">
	<h3 class="sheet_header">Campaigns</h3>
	
		<%  @group.created_campaigns.map do |created_campaigns| %>
			<div class="profile_list">
				<%= link_to h(created_campaigns.title), created_campaigns%>
			</div>
		<% end %>
</div>

<div class="section">
	<h3 class="sheet_header">Members</h3>
<% @group.users.map do |user| %>
	<div class="profile_list">
	<table>
		<tr>
			<td class="description">
				<% if user.gender == "Female"%>
					<img src="/images/profile_female.png" alt"group photo" width="50px" />
				<% else %>
					<img src="/images/profile_male.png" alt"group photo" width="50px" />
				<% end %>
			</td>
			<td>
				<table>
					<tr>
						<td class="description"> Name:</td>
						<td><strong><%= link_to h(user.name), user %></strong></td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
	</div>
<% end %>
</div>


</div>