config/routes.rb
RPGalot::Application.routes.draw do 
  resources :languages

  resources :levels

	root :to => 'home#index'
	
	match "login" => "user_sessions#new", :as => "login"
  match "logout" => "user_sessions#destroy", :as => "logout"

 	resources :user_sessions
  resources :character_feats
  resources :weapons
  resources :races
	resources :feats
  resources :deities
  resources :klass_skills
  resources :klass_alignments
  resources :klasses
  resources :alignments
  resources :skills
  resources :abilities
  resources :games
  resources :characters
  resources :campaigns
  resources :memberships
  resources :groups
  resources :users


	#map.connect ':controller/:action/:id'

  #map.connect ':controller/:action/:id.:format'
end

app/models/alignment.rb
class Alignment < ActiveRecord::Base
	
	has_many :klass_alignments
	has_many :klasses, :through => :klass_alignments
end

app/controllers/alignments_controller.rb
class AlignmentsController < ApplicationController
  # GET /alignments
  # GET /alignments.xml
  def index
    @alignments = Alignment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @alignments }
    end
  end

  # GET /alignments/1
  # GET /alignments/1.xml
  def show
    @alignment = Alignment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @alignment }
    end
  end

  # GET /alignments/new
  # GET /alignments/new.xml
  def new
    @alignment = Alignment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @alignment }
    end
  end

  # GET /alignments/1/edit
  def edit
    @alignment = Alignment.find(params[:id])
  end

  # POST /alignments
  # POST /alignments.xml
  def create
    @alignment = Alignment.new(params[:alignment])

    respond_to do |format|
      if @alignment.save
        format.html { redirect_to(@alignment, :notice => 'Alignment was successfully created.') }
        format.xml  { render :xml => @alignment, :status => :created, :location => @alignment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @alignment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /alignments/1
  # PUT /alignments/1.xml
  def update
    @alignment = Alignment.find(params[:id])

    respond_to do |format|
      if @alignment.update_attributes(params[:alignment])
        format.html { redirect_to(@alignment, :notice => 'Alignment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @alignment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /alignments/1
  # DELETE /alignments/1.xml
  def destroy
    @alignment = Alignment.find(params[:id])
    @alignment.destroy

    respond_to do |format|
      format.html { redirect_to(alignments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/alignments_helper.rb
module AlignmentsHelper
end

app/views/alignments/edit.html.erb
<div class="content">
<h1>Editing alignment</h1>

<%= form_for(@alignment) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @alignment %> |
<%= link_to 'Back', alignments_path %>
</div>

app/views/alignments/index.html.erb
<div class="content">
<h1>Listing alignments</h1>

<table>
  <tr>
    <th>Title</th>
  </tr>

<% @alignments.each do |alignment| %>
  <tr>
    <td><%=h alignment.title %></td>
    <td><%= link_to 'Show', alignment %></td>
    <td><%= link_to 'Edit', edit_alignment_path(alignment) %></td>
    <td><%= link_to 'Destroy', alignment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New alignment', new_alignment_path %>
</div>

app/views/alignments/new.html.erb
<div class="content">
<h1>New alignment</h1>

<%= form_for(@alignment) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', alignments_path %>
</div>

app/views/alignments/show.html.erb
<div class="content">
<p>
  <b>Title:</b>
  <%=h @alignment.title %>
</p>


<%= link_to 'Edit', edit_alignment_path(@alignment) %> |
<%= link_to 'Back', alignments_path %>
</div>