config/routes.rb
RPGalot::Application.routes.draw do 
  resources :languages

  resources :levels

	root :to => 'home#index'
	
	match "login" => "user_sessions#new", :as => "login"
  match "logout" => "user_sessions#destroy", :as => "logout"

 	resources :user_sessions
  resources :character_feats
  resources :weapons
  resources :races
	resources :feats
  resources :deities
  resources :klass_skills
  resources :klass_alignments
  resources :klasses
  resources :alignments
  resources :skills
  resources :abilities
  resources :games
  resources :characters
  resources :campaigns
  resources :memberships
  resources :groups
  resources :users


	#map.connect ':controller/:action/:id'

  #map.connect ':controller/:action/:id.:format'
end

app/models/game.rb
class Game < ActiveRecord::Base
	
	# t.string :title, :null => false
	# t.string :url, :null => false
	
	validates_presence_of :title, :url
	has_many :weapons, :class_name => 'Weapon', :foreign_key => :game_id
	has_many :skills, :class_name => 'Skill', :foreign_key => :game_id
	has_many :races, :class_name => 'Race', :foreign_key => :game_id
	has_many :klasses, :class_name => 'Klass', :foreign_key => :game_id
	has_many :feats, :class_name => 'Feat', :foreign_key => :game_id
	has_many :deities, :class_name => 'Deity', :foreign_key => :game_id
	has_many :alignments, :class_name => 'Alignment', :foreign_key => :game_id
	has_many :languages, :class_name => 'Language', :foreign_key => :game_id
end

app/controllers/klasses_controller.rb
class KlassesController < ApplicationController
  # GET /klasses
  # GET /klasses.xml
  def index
    @klasses = Klass.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @klasses }
    end
  end

  # GET /klasses/1
  # GET /klasses/1.xml
  def show
    @klass = Klass.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @klass }
    end
  end

  # GET /klasses/new
  # GET /klasses/new.xml
  def new
    @klass = Klass.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @klass }
    end
  end

  # GET /klasses/1/edit
  def edit
    @klass = Klass.find(params[:id])
  end

  # POST /klasses
  # POST /klasses.xml
  def create
    @klass = Klass.new(params[:klass])

    respond_to do |format|
      if @klass.save
        format.html { redirect_to(@klass, :notice => 'Klass was successfully created.') }
        format.xml  { render :xml => @klass, :status => :created, :location => @klass }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @klass.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /klasses/1
  # PUT /klasses/1.xml
  def update
    @klass = Klass.find(params[:id])

    respond_to do |format|
      if @klass.update_attributes(params[:klass])
        format.html { redirect_to(@klass, :notice => 'Klass was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @klass.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /klasses/1
  # DELETE /klasses/1.xml
  def destroy
    @klass = Klass.find(params[:id])
    @klass.destroy

    respond_to do |format|
      format.html { redirect_to(klasses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/klasses_helper.rb
module KlassesHelper
end

app/views/klasses/_form.html.erb
<% f.inputs do %>
  <%= f.input :title %>
  <%= f.input :hit_die, :as => :select, :collection =>[4,6,8,10,12] %>
  <%= f.input :skill_points, :as => :select, :collection =>[2,4,6,8] %>
  <%= f.input :attack_bonus, :as => :select, :collection => {'Good' => 1, 'Average' => 2, 'Poor' => 3} %>

	<p>Check off the major saves for this class</p>
  <%= f.input :fort_save %>
  <%= f.input :ref_save %>
  <%= f.input :will_save %>

	<%= f.input :alignment_ids, :as => :check_boxes, :collection => Alignment.all, :label => 'Class Alignments'  %>
	<%= f.input :skill_ids, :as => :check_boxes, :collection => Skill.all, :label => 'Class Skills'  %>
	

	<% f.buttons do %>
	  <%= f.commit_button %>
	<% end %>
<% end %>

app/views/klasses/edit.html.erb
<h1>Editing klass</h1>

<%= semantic_form_for(@klass) do |f| %>
      <%= render 'form', :f => f %>
<% end %>

<%= link_to 'Show', @klass %> |
<%= link_to 'Back', klasses_path %>

app/views/klasses/index.html.erb
<h1>Listing klasses</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Hit die</th>
    <th>Skill points</th>
    <th>Attack bonus</th>
    <th>Fort save</th>
    <th>Ref save</th>
    <th>Will save</th>
  </tr>

<% @klasses.each do |klass| %>
  <tr>
    <td><%=h klass.title %></td>
    <td><%=h klass.hit_die %></td>
    <td><%=h klass.skill_points %></td>
    <td><%=h klass.attack_bonus %></td>
    <td><%=h klass.fort_save %></td>
    <td><%=h klass.ref_save %></td>
    <td><%=h klass.will_save %></td>
    <td><%= link_to 'Show', klass %></td>
    <td><%= link_to 'Edit', edit_klass_path(klass) %></td>
    <td><%= link_to 'Destroy', klass, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New klass', new_klass_path %>

app/views/klasses/new.html.erb
<h1>New klass</h1>

<%= semantic_form_for(@klass) do |f| %>
      <%= render 'form', :f => f %>
<% end %>

<%= link_to 'Back', klasses_path %>

app/views/klasses/show.html.erb
<p>
  <b>Class Name:</b>
  <%=h @klass.title %>
</p>

<p>
  <b>Hit die:</b>
  <%=h @klass.hit_die %>
</p>

<p>
  <b>Skill points:</b>
  <%=h @klass.skill_points %>
</p>

<p>
  <b>Attack bonus:</b>
  <%=h @klass.attack_bonus %>
</p>

<p>
  <b>Fort save:</b>
  <%=h @klass.fort_save %>
</p>

<p>
  <b>Ref save:</b>
  <%=h @klass.ref_save %>
</p>

<p>
  <b>Will save:</b>
  <%=h @klass.will_save %>
</p>

<p>
	<b>Class Alignments:</b>
		<%= 
			@klass.alignments.map do |alignment|
				h(alignment.title)
			end.join(', ')
		%>
</p>
<p>
	<b>Class Skills:</b>
		<%= @klass.skills.map do |skill|
				h(skill.fancy_name+" ("+skill.ability+")")
			 end.join(', ')
				%>
</p>

<%= link_to 'Edit', edit_klass_path(@klass) %> |
<%= link_to 'Back', klasses_path %>